version: "3"

services:

  namenode:
    image: ghcr.io/ezynook/ezynook.github.io/app:namenode
    container_name: namenode
    volumes:
      - ./namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=PasitCloud
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"

  datanode:
    image: ghcr.io/ezynook/ezynook.github.io/app:datanode
    container_name: datanode
    volumes:
      - ./datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"

  hive-server:
    image: ghcr.io/ezynook/ezynook.github.io/app:hive-server
    container_name: hive
    env_file:
      - ./hadoop-hive.env
    volumes:
      - ./tmp:/tmp
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    image: ghcr.io/ezynook/ezynook.github.io/app:hive-metastore
    container_name: hive2
    env_file:
      - ./hadoop-hive.env
    volumes:
      - ./tmp:/tmp
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: ghcr.io/ezynook/ezynook.github.io/app:postgres-metastore
    container_name: postgresql
    
  presto-coordinator:
    image: ghcr.io/ezynook/ezynook.github.io/app:prestodb
    container_name: prestodb
    ports:
      - "8080:8080"